export const USER_GEOL_CHNG = 'user_geol_chng'
export const USER_ADDR_CHNG = 'user_addr_chng'
export const USER_LOGIN_SUCCESS = 'user_login_success'
export const USER_LOGIN_FAIL = 'user_login_fail'
export const USER_LOGIN = 'user_login'
export const USER_LOGIN_STILL = 'user_login_still'
export const USER_LOGOUT_SUCCESS = 'user_logout_success'
export const USER_LOGOUT_FAIL = 'user_logout_fail'
export const USER_LOGOUT = 'user_logout'

export const MAP_REGN_CHNG = 'map_regn_chng'
export const MAP_ADDR_CHNG = 'map_addr_chng'
export const MAP_REF_SAVE = 'map_ref_save'
